/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.order;

import app.listener.ContentListener;
import app.listener.IImportOrderListener;
import java.awt.BorderLayout;

/**
 *
 * @author Administrator
 */
public class ImportOrderContent extends javax.swing.JPanel implements IImportOrderListener {

    private ImportOrderTable importOrderTable;
    private ImportOrderForm importOrderForm;
    private ImportOrderMenu importOrderMenu;
    private ContentListener listener;

    public void setListener(ContentListener listener) {
        this.listener = listener;
    }

    /**
     * Creates new form ImportOrderContent
     */
    public ImportOrderContent() {
        initComponents();
        
    }
    public void init(){
        viewImportOrderMenu();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void viewImportOrderTable() {
        if (importOrderTable == null) {
            importOrderTable = new ImportOrderTable();
            importOrderTable.setListener(this);
        }
        this.removeAll();
        this.add(importOrderTable, BorderLayout.CENTER);
        listener.changepanel();
    }

    @Override
    public void viewImportOrderForm() {
        if (importOrderForm == null) {
            importOrderForm = new ImportOrderForm();
            importOrderForm.setListener(this);
        }
        this.removeAll();
        this.add(importOrderForm, BorderLayout.CENTER);
        listener.changepanel();
    }

    @Override
    public void viewImportOrderMenu() {
        if (importOrderMenu == null) {
            importOrderMenu = new ImportOrderMenu();
            importOrderMenu.setListener(this);
        }
        this.removeAll();
        this.add(importOrderMenu, BorderLayout.CENTER);
        listener.changepanel();
    }
}
