/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.component.report;

import java.sql.Date;
import java.util.Calendar;
import javax.swing.JPanel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ShowroomReport extends javax.swing.JPanel {

    /**
     * Creates new form ShowroomReport
     */
    public ShowroomReport() {
        initComponents();
        lib = new StatisticLib();
        initCbb();
    }
    private StatisticLib lib;

    private void initCbb() {
        jComboBox1.removeAllItems();
        for (String item : lib.getListCategory()) {
            jComboBox1.addItem(item);
        }
        jComboBox3.removeAllItems();
        jComboBox3.addItem("Date");
        jComboBox3.addItem("Month");
        jComboBox3.addItem("Year");
    }

    private int getStepInt(String step) {
        if (step.equals("Year")) {
            return 3;
        } else if (step.equals("Month")) {
            return 2;
        } else {
            return 1;
        }
    }
    private JPanel activePanel;

    private void changePanelReport(JPanel panel) {
        jPanel2.removeAll();
        jPanel2.add(panel);
        activePanel = panel;
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    private void activeStatistic(int constant) {
        Date from = null;
        Date to = null;
        Calendar fromCal = jDateChooser1.getCalendar();
        if (fromCal != null) {
            from = new Date(fromCal.getTimeInMillis());
        }
        Calendar toCal = jDateChooser2.getCalendar();
        if (toCal != null) {
            to = new Date(toCal.getTimeInMillis());
        }
        if ((from != null && to == null && from.getTime() > new Date((new java.util.Date().getTime())).getTime()) || (from != null && to != null && from.getTime() > to.getTime())) {
            JOptionPane.showMessageDialog(this, "Warning : From time greater To time.");
        }
        String detailsstatic = (String) jComboBox2.getSelectedItem();
        int select = lib.getConstantByString(detailsstatic);
        switch (constant) {
            case StatisticLib.CATEGORY_VEHICLE:
                StatisticVehicle sv = new StatisticVehicle();
                sv.setFrom(from);
                sv.setTo(to);
                sv.setStep(getStepInt((String) jComboBox3.getSelectedItem()));
                sv.showStatistic(select);
                activePanel = sv;
                break;
            case StatisticLib.CATEGORY_ORDER:
                StatisticOrder so = new StatisticOrder();
                so.setFrom(from);
                so.setTo(to);
                so.setStep(getStepInt((String) jComboBox3.getSelectedItem()));
                so.showStatistic(select);
                activePanel = so;
                break;
            case StatisticLib.CATEGORY_IMPORTORDER:
                StatisticImportOrder sio = new StatisticImportOrder();
                sio.setFrom(from);
                sio.setTo(to);
                sio.setStep(getStepInt((String) jComboBox3.getSelectedItem()));
                sio.showStatistic(select);
                activePanel = sio;
                break;
            case StatisticLib.CATEGORY_CUSTOMER:
                StatisticCustomer sc = new StatisticCustomer();
                sc.setFrom(from);
                sc.setTo(to);
                sc.setStep(getStepInt((String) jComboBox3.getSelectedItem()));
                sc.showStatistic(select);
                activePanel = sc;
                break;
            case StatisticLib.CATEGORY_DEALER:
                StatisticDealer sd = new StatisticDealer();
                sd.setFrom(from);
                sd.setTo(to);
                sd.setStep(getStepInt((String) jComboBox3.getSelectedItem()));
                sd.showStatistic(select);
                activePanel = sd;
                break;
            default:
                break;
        }
        changePanelReport(activePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());
        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel1.setText("From :");

        jLabel2.setText("To :");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jButton1.setText("Show Me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Step :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selected = (String) jComboBox1.getSelectedItem();
        int constant = lib.getConstantByString(selected);
        if (constant == -1) {
            return;
        }
        activeStatistic(constant);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String selected = (String) jComboBox1.getSelectedItem();
        int constant = lib.getConstantByString(selected);
        if (constant == -1) {
            return;
        }
        List<String> sublst = null;
        sublst = lib.getSubListofCategory(constant);
        jComboBox2.removeAllItems();
        for (String string : sublst) {
            jComboBox2.addItem(string);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
