/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.composite;

/**
 *
 * @author Administrator
 */
public class CustomerManage extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomer
     */
    public CustomerManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerTable1 = new app.view.component.customer.CustomerTable();

        setLayout(new java.awt.BorderLayout());
        add(customerTable1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.view.component.customer.CustomerTable customerTable1;
    // End of variables declaration//GEN-END:variables
}
