/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.composite;

import app.icomponent.IPanelTable;
import app.model.Customer;
import app.model.Vehicle;
import app.service.CustomerService;
import app.service.OrderService;
import app.service.VehicleService;
import app.view.component.customer.CustomerTable;
import app.view.component.customer.CustomerTableForSales;
import app.view.component.vehicle.VehicleTable;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SalesVehicle extends javax.swing.JPanel {

    private VehicleService vehicleService;
    private OrderService orderService;
    private CustomerService customerService;
    private VehicleTable vehicleTable;
    private CustomerTableForSales customerTable;
    private IPanelTable activeTable;

    /**
     * Creates new form SalesVehicle
     */
    public SalesVehicle() {
        initComponents();
        vehicleService = new VehicleService();
        orderService = new OrderService();
        customerService = new CustomerService();
        viewTableVehicle();
    }

    public void viewTableVehicle() {
        if (vehicleTable == null) {
            vehicleTable = new VehicleTable();
            reloadTableVehicle();
        }
        activeTable = vehicleTable;
        jPanel1.removeAll();
        jPanel1.add(vehicleTable);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void reloadTableVehicle() {
        List<Vehicle> vehicles = vehicleService.getAll();
        vehicleTable.setModel(vehicles);
    }

    public void viewTableCustomer() {
        if (customerTable == null) {
            customerTable = new CustomerTableForSales();
            reloadTableCustomer();
        }
        activeTable = customerTable;
        jPanel1.removeAll();
        jPanel1.add(customerTable);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void reloadTableCustomer() {
        List<Customer> customers = customerService.getAll();
        customerTable.setModel(customers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        orderForm1 = new app.view.component.invoice.OrderForm();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.FlowLayout(0));

        jTextField1.setText("For Search");
        jTextField1.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel4.add(jTextField1);

        jButton1.setText("Search");
        jPanel4.add(jButton1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox1);

        jButton2.setText("Load Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox2);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(orderForm1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Object selectobj = activeTable.getSelectedObject();
        if (selectobj instanceof Vehicle) {
            Vehicle temp = (Vehicle) selectobj;
            if (temp.getQuantity() <= 0) {
                JOptionPane.showMessageDialog(this, "This Model Number is not avaiable.");
                return;
            }
        }
        if (selectobj != null) {
            orderForm1.setDataModel(selectobj);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (activeTable instanceof VehicleTable) {
            reloadTableVehicle();
        }
        if (activeTable instanceof CustomerTableForSales) {
            reloadTableCustomer();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private app.view.component.invoice.OrderForm orderForm1;
    // End of variables declaration//GEN-END:variables
}
