/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.composite;

import app.icomponent.IPanelTable;
import app.model.Customer;
import app.model.Vehicle;
import app.service.CustomerService;
import app.service.OrderService;
import app.service.VehicleService;
import app.view.Main;
import app.view.component.customer.CustomerTable;
import app.view.component.customer.CustomerTableForSales;
import app.view.component.vehicle.VehicleTable;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SalesVehicle extends javax.swing.JPanel {

    private VehicleService vehicleService;
    private OrderService orderService;
    private CustomerService customerService;

    /**
     * Creates new form SalesVehicle
     */
    public SalesVehicle() {
        initComponents();
        vehicleService = new VehicleService();
        orderService = new OrderService();
        customerService = new CustomerService();
        viewTableVehicle();
    }
    AtomicReference<Integer> totalpage = new AtomicReference<Integer>(0);
    int curpage = 1;
    String search = "";

    public void setTotalpage(Integer totalpage) {
        this.totalpage.set(totalpage);
        fillPage();
    }

    public void setCurpage(int curpage) {
        this.curpage = curpage;
        if (activeTable instanceof VehicleTable) {
            fillDataVehicle(curpage);
        } else {
            fillDataCustomer(curpage);
        }
    }

    private void fillDataVehicle(int page) {
        String pagingsql = "";
        if (search.equals("")) {
            pagingsql = vehicleService.BuildPagingSql(vehicleService.getTableName(), null, Main.PerPage, page, totalpage);
        } else {
            pagingsql = vehicleService.BuildPagingSql(vehicleService.getTableName(), vehicleService.getConditionSearch(search), Main.PerPage, page, totalpage);
        }
        List<Vehicle> lst = vehicleService.executeQuery(pagingsql);
        vehicleTable.setModel(lst);
    }

    private void fillDataCustomer(int page) {
        String pagingsql = "";
        if (search.equals("")) {
            pagingsql = customerService.BuildPagingSql(customerService.getTableName(), null, Main.PerPage, page, totalpage);
        } else {
            pagingsql = customerService.BuildPagingSql(customerService.getTableName(), customerService.getConditionSearch(search), Main.PerPage, page, totalpage);
        }
        List<Customer> lst = customerService.executeQuery(pagingsql);
        customerTable.setModel(lst);
    }

    private void fillPage() {
        jComboBox1.removeAllItems();
        for (int i = 1; i <= totalpage.get(); i++) {
            jComboBox1.addItem(i);
        }
        jComboBox1.setSelectedItem(curpage);
        jComboBox1.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                Object temppage = jComboBox1.getSelectedItem();
                if (temppage != null) {
                    setCurpage((Integer) temppage);
                }
            }
        });
        jComboBox1.revalidate();
        jComboBox1.repaint();
    }
    private VehicleTable vehicleTable;
    private CustomerTableForSales customerTable;
    private IPanelTable activeTable;

    public void viewTableVehicle() {
        if (vehicleTable == null) {
            vehicleTable = new VehicleTable();
            reloadTableVehicle();
        }
        activeTable = vehicleTable;
        jPanel1.removeAll();
        jPanel1.add(vehicleTable);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void reloadTableVehicle() {
        search = "";
        jTextField1.setText(search);
        fillDataVehicle(1);
        fillPage();
    }

    public void viewTableCustomer() {
        if (customerTable == null) {
            customerTable = new CustomerTableForSales();
            reloadTableCustomer();
        }
        activeTable = customerTable;
        jPanel1.removeAll();
        jPanel1.add(customerTable);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void reloadTableCustomer() {
        search = "";
        jTextField1.setText(search);
        fillDataCustomer(1);
        fillPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        orderForm1 = new app.view.component.invoice.OrderForm();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.FlowLayout(0));
        jPanel4.add(jComboBox1);

        jTextField1.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel4.add(jTextField1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton2.setText("Load Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(orderForm1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Object selectobj = activeTable.getSelectedObject();
        if (selectobj instanceof Vehicle) {
            Vehicle temp = (Vehicle) selectobj;
            if (temp.getQuantity() <= 0) {
                JOptionPane.showMessageDialog(this, "This Model Number is not avaiable.");
                return;
            }
        }
        if (selectobj != null) {
            orderForm1.setDataModel(selectobj);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (activeTable instanceof VehicleTable) {
            reloadTableVehicle();
        }
        if (activeTable instanceof CustomerTableForSales) {
            reloadTableCustomer();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        search = jTextField1.getText();
        if (activeTable instanceof VehicleTable) {
            fillDataVehicle(1);
            fillPage();
        }
        if (activeTable instanceof CustomerTableForSales) {
            fillDataCustomer(1);
            fillPage();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private app.view.component.invoice.OrderForm orderForm1;
    // End of variables declaration//GEN-END:variables
}
