/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.component.brand;

import app.model.Brand;
import app.model.Vehicle;
import app.service.BrandService;
import app.view.Main;
import app.view.model.TableBrandModel;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

/**
 *
 * @author Administrator
 */
public class BrandManage extends javax.swing.JPanel {

    public void reloadData() {
        fillData(curpage);
        fillPage();
    }

    public void refresh() {
        search = "";
        jTextField1.setText(search);
        fillData(1);
        fillPage();
    }
    AtomicReference<Integer> totalpage = new AtomicReference<Integer>(0);
    int curpage = 1;
    String search = "";
    TableBrandModel model = new TableBrandModel();

    public void setTotalpage(Integer totalpage) {
        this.totalpage.set(totalpage);
        fillPage();
    }

    public void setCurpage(int curpage) {
        this.curpage = curpage;
        fillData(curpage);
    }

    private void fillData(int page) {
        String pagingsql = "";
        if (search.equals("")) {
            pagingsql = brandService.BuildPagingSql(brandService.getTableName(), null, Main.PerPage, page, totalpage);
        } else {
            pagingsql = brandService.BuildPagingSql(brandService.getTableName(), brandService.getConditionSearch(search), Main.PerPage, page, totalpage);
        }
        List<Brand> lst = brandService.executeQuery(pagingsql);
        brandTable1.setModel(lst);
        brandTable1.revalidate();
        brandTable1.repaint();
    }

    private int getTotalPage() {
        int temptotal = totalpage.get();
        int temp = temptotal % Main.PerPage;
        if (temp == 0) {
            return (temptotal / Main.PerPage);
        } else {
            return (temptotal / Main.PerPage) + 1;
        }
    }

    private void fillPage() {
        jComboBox1.removeAllItems();
        for (int i = 1; i <= getTotalPage(); i++) {
            jComboBox1.addItem(i);
        }
        jComboBox1.setSelectedItem(curpage);
        jComboBox1.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                Object temppage = jComboBox1.getSelectedItem();
                if (temppage != null) {
                    setCurpage((Integer) temppage);
                }
            }
        });
        jComboBox1.revalidate();
        jComboBox1.repaint();
    }
    
    private BrandService brandService;
    
    /**
     * Creates new form BrandManage
     */
    public BrandManage() {
        initComponents();
        brandService = new BrandService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        brandTable1 = new app.view.component.brand.BrandTable();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.FlowLayout(0));
        jPanel5.add(jComboBox1);

        jTextField1.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel5.add(jTextField1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton2.setText("New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton3.setText("Edit");
        jPanel5.add(jButton3);

        jButton4.setText("Details");
        jPanel5.add(jButton4);

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);

        add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(brandTable1, java.awt.BorderLayout.CENTER);

        add(jPanel6, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        search = jTextField1.getText();
        fillData(1);
        fillPage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BrandDialog dialog=new BrandDialog(null, true);
        dialog.setLocationRelativeTo(null);
        dialog.callToCreateNew();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.view.component.brand.BrandTable brandTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
