/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.vehicle;

import app.view.order.*;
import app.listener.ContentListener;
import app.listener.*;
import java.awt.BorderLayout;

/**
 *
 * @author Administrator
 */
public class ImportVehicleContent extends javax.swing.JPanel implements IImportVehicleListener {

    private ImportVehicleTable importVehicleTable;
    private ImportVehicleForm importVehicleForm;
    private ImportVehicleMenu importVehicleMenu;
    private ContentListener listener;

    public void setListener(ContentListener listener) {
        this.listener = listener;
    }

    /**
     * Creates new form ImportOrderContent
     */
    public ImportVehicleContent() {
        initComponents();
        
    }
    public void init(){
        viewImportVehicleMenu();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void viewImportVehicleTable() {
        if (importVehicleTable == null) {
            importVehicleTable = new ImportVehicleTable();
            importVehicleTable.setListener(this);
        }
        this.removeAll();
        this.add(importVehicleTable, BorderLayout.CENTER);
        listener.changepanel();
    }

    @Override
    public void viewImportVehicleForm() {
        if (importVehicleMenu == null) {
            importVehicleMenu = new ImportVehicleMenu();
            importVehicleMenu.setListener(this);
        }
        this.removeAll();
        this.add(importVehicleMenu, BorderLayout.CENTER);
        listener.changepanel();
    }

    @Override
    public void viewImportVehicleMenu() {
        if (importVehicleMenu == null) {
            importVehicleMenu = new ImportVehicleMenu();
            importVehicleMenu.setListener(this);
        }
        this.removeAll();
        this.add(importVehicleMenu, BorderLayout.CENTER);
        listener.changepanel();
    }
}
