/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.view.component.dealer.DealerManager;

/**
 *
 * @author Administrator
 */
public class AdminManageV2 extends javax.swing.JPanel {

    private DealerManager dealerManager;

    /**
     * Creates new form AdminManageV2
     */
    public AdminManageV2() {
        initComponents();
        viewDealerManage();
    }

    private void viewDealerManage() {
        if (dealerManager == null) {
            dealerManager = new DealerManager();
        }
        dealerManager.reload();
        mainpanel.removeAll();
        mainpanel.add(dealerManager);
        mainpanel.revalidate();
        mainpanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnVehicle2 = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        mainpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainpanel.setLayout(new java.awt.BorderLayout());

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(0, 102, 0));
        lbTitle.setText("Vehicle Showroom Management");
        mainpanel.add(lbTitle, java.awt.BorderLayout.PAGE_START);

        add(mainpanel, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVehicle2.setText("Dealer");
        btnVehicle2.setPreferredSize(new java.awt.Dimension(100, 40));
        btnVehicle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicle2ActionPerformed(evt);
            }
        });

        btnCustomer.setText("Report");
        btnCustomer.setPreferredSize(new java.awt.Dimension(100, 40));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVehicle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVehicle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehicle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicle2ActionPerformed
        // TODO add your handling code here:
        viewDealerManage();
    }//GEN-LAST:event_btnVehicle2ActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCustomerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnVehicle2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
