/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.listener.ContentListener;
import app.listener.IImportOrderListener;
import app.view.order.ImportOrderContent;
import app.view.order.ImportOrderForm;
import app.view.order.ImportOrderTable;
import app.view.invoice.ImportOrderPlusContent;
import app.view.vehicle.ImportVehicleContent;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame implements ContentListener{

    //private ImportVehicleContent importOrderContent;
    private ImportOrderPlusContent importOrderContent;
    private ImportVehicleContent importVehicleContent;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        callInvoice();
        callVehicle();
    }
    public void callInvoice(){
        importOrderContent = new ImportOrderPlusContent();
        importOrderContent.setListener(this);
        importOrderContent.init();
        panelInvoice.add(importOrderContent);
    }
    public void callVehicle(){
        importVehicleContent = new ImportVehicleContent();
        importVehicleContent.setListener(this);
        importVehicleContent.init();
        panelVehicle.add(importVehicleContent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        panelVehicle = new javax.swing.JPanel();
        panelInvoice = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Showroom Management");
        setMinimumSize(new java.awt.Dimension(1000, 600));

        tabPanel.setMinimumSize(new java.awt.Dimension(800, 1000));
        tabPanel.addTab("Vehicle", panelVehicle);
        tabPanel.addTab("Invoice", panelInvoice);

        getContentPane().add(tabPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainframe = new MainFrame();
                mainframe.setVisible(true);
                mainframe.setLocationRelativeTo(null);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelInvoice;
    private javax.swing.JPanel panelVehicle;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void changepanel() {
        this.revalidate();
        this.repaint();
    }
}
