/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.view.component.customer.CustomerTable;
import app.view.component.vehicle.VehicleManagement;
import app.view.composite.ImportOrderManage;

/**
 *
 * @author Administrator
 */
public class ManageShowroomV2 extends javax.swing.JPanel {

    private VehicleManagement vehicleManagement;
    private ImportOrderManage importOrderManage;
    private CustomerTable customerTable;

    /**
     * Creates new form ManageShowroomV2
     */
    public ManageShowroomV2() {
        initComponents();
        viewVehicleManagement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVehicle = new javax.swing.JButton();
        btnOrders = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        mainpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainpanel.setLayout(new java.awt.BorderLayout());

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(0, 102, 0));
        lbTitle.setText("Vehicle Showroom Management");
        mainpanel.add(lbTitle, java.awt.BorderLayout.PAGE_START);

        add(mainpanel, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVehicle.setText("Vehicles");
        btnVehicle.setPreferredSize(new java.awt.Dimension(100, 40));
        btnVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleActionPerformed(evt);
            }
        });

        btnOrders.setText("Orders");
        btnOrders.setPreferredSize(new java.awt.Dimension(100, 40));
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });

        btnCustomer.setText("Customers");
        btnCustomer.setPreferredSize(new java.awt.Dimension(100, 40));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleActionPerformed
        viewVehicleManagement();
    }//GEN-LAST:event_btnVehicleActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        // TODO add your handling code here:
        viewImportOrderManagement();
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        viewCustomerManagement();
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void viewVehicleManagement() {
        mainpanel.removeAll();
        if (vehicleManagement == null) {
            vehicleManagement = new VehicleManagement();
        }
        mainpanel.add(vehicleManagement);
        lbTitle.setText("Vehicle Management");
        mainpanel.revalidate();
        mainpanel.repaint();
    }
    private void viewImportOrderManagement() {
        mainpanel.removeAll();
        if (importOrderManage == null) {
            importOrderManage = new ImportOrderManage();
        }
        mainpanel.add(importOrderManage);
        lbTitle.setText("Import Order Management");
        mainpanel.revalidate();
        mainpanel.repaint();
    }
    private void viewCustomerManagement() {
        mainpanel.removeAll();
        if (customerTable == null) {
            customerTable = new CustomerTable();
        }
        mainpanel.add(customerTable);
        lbTitle.setText("Customer Management");
        mainpanel.revalidate();
        mainpanel.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnVehicle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
