/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.service.OrderService;
import app.service.VehicleService;
import app.view.component.report.DealerReport;
import app.view.composite.OrderForCustomer;
import app.view.composite.SalesOrder;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class SalesServiceV2 extends javax.swing.JPanel {

    private VehicleService vehicleService;
    private OrderService orderService;
    private JPanel activePanel;
    private SalesOrder salesOrder;
    private DealerReport report;
    private OrderForCustomer orderForCustomer;

    /**
     * Creates new form SalesServiceV2
     */
    public SalesServiceV2() {
        initComponents();
        showOrderForCustomerView();
    }

    private void showOrderForCustomerView() {
        if (orderForCustomer == null) {
            orderForCustomer = new OrderForCustomer();
        }
        activePanel = orderForCustomer;
        orderForCustomer.reloadData();
        mainpanel.removeAll();
        mainpanel.add(orderForCustomer);
        mainpanel.revalidate();
        mainpanel.repaint();
    }

    public void showInvoiceView() {
        if (salesOrder == null) {
            salesOrder = new SalesOrder();
        }
        activePanel = salesOrder;
        salesOrder.reloadTableOrder();
        mainpanel.removeAll();
        mainpanel.add(salesOrder);
        mainpanel.revalidate();
        mainpanel.repaint();
    }

    public void showDealerReportView() {
        if (report == null) {
            report = new DealerReport();
        }
        activePanel = report;
        mainpanel.removeAll();
        mainpanel.add(report);
        mainpanel.revalidate();
        mainpanel.repaint();
    }

    public void BodyChanged() {
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnOrders = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnCreateOrder = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new java.awt.BorderLayout());

        mainpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainpanel.setLayout(new java.awt.BorderLayout());

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(0, 102, 0));
        lbTitle.setText("Vehicle Showroom Management");
        mainpanel.add(lbTitle, java.awt.BorderLayout.PAGE_START);

        add(mainpanel, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOrders.setText("Update Order");
        btnOrders.setPreferredSize(new java.awt.Dimension(100, 40));
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });

        btnReport.setText("Report");
        btnReport.setPreferredSize(new java.awt.Dimension(100, 40));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnCreateOrder.setText("Create Order");
        btnCreateOrder.setPreferredSize(new java.awt.Dimension(100, 40));
        btnCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(btnCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        // TODO add your handling code here:
        showInvoiceView();
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        showDealerReportView();
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
        // TODO add your handling code here:
        showOrderForCustomerView();
    }//GEN-LAST:event_btnCreateOrderActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnReport;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
