/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.listener.IMainFrame;
import app.listener.ISalesService;
import app.view.invoice.ImportOrderPlusContent;
import app.view.vehicle.ImportVehicleContent;

/**
 *
 * @author Administrator
 */
public class SalesService extends javax.swing.JPanel implements ISalesService{

    private ImportOrderPlusContent importOrderContent;
    private ImportVehicleContent importVehicleContent;
    private IMainFrame listener;

    public void setListener(IMainFrame listener) {
        this.listener = listener;
    }
    
    /**
     * Creates new form SalesService
     */
    public SalesService() {
        initComponents();
        callInvoice();
    }

    public void callInvoice() {
        importOrderContent = new ImportOrderPlusContent();
        importOrderContent.init();
        panelInvoice.add(importOrderContent);
        BodyChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInvoice = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());
        add(panelInvoice, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelInvoice;
    // End of variables declaration//GEN-END:variables

    @Override
    public void BodyChanged() {
        this.revalidate();
        this.repaint();
    }

}
