/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.component.vehicle;

import app.model.Vehicle;
import app.service.VehicleService;
import app.view.Main;
import app.view.component.order.DialogImportOrderForm;
import app.view.model.TableVehicleModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.JOptionPane;

/**
 *
 * @author kiendv
 */
public class VehicleManagement extends javax.swing.JPanel {

    VehicleService service;
    TableVehicleModel tableModel = new TableVehicleModel();

    /**
     * Creates new form VehicleManagement
     */
    public VehicleManagement() {
        initComponents();
        service = new VehicleService();
        initCbbFilter();
        setCurpage(1);
        fillPage();
    }

    private void initCbbFilter() {
        cbbrand.removeAllItems();
        List<String> brands = service.getListBrandName();
        cbbrand.addItem(Main.ALL);
        for (String brand : brands) {
            cbbrand.addItem(brand);
        }
        cbbrand.revalidate();
        cbbrand.repaint();

        cbbcategory.removeAllItems();
        List<String> categorys = service.getListCategoryName();
        cbbcategory.addItem(Main.ALL);
        for (String category : categorys) {
            cbbcategory.addItem(category);
        }
    }
    AtomicReference<Integer> totalpage = new AtomicReference<Integer>(0);
    int curpage = 1;
    String search = "";

    public void setTotalpage(Integer totalpage) {
        this.totalpage.set(totalpage);
        fillPage();
    }

    public void setCurpage(int curpage) {
        this.curpage = curpage;
        fillData(curpage);
    }

    private void fillData(int page) {
        String pagingsql = "";
        String brand = (String) cbbrand.getSelectedItem();
        String category = (String) cbbcategory.getSelectedItem();
        if (search.equals("")) {
            pagingsql = service.BuildPagingSql(service.getTableName(), service.getConditionFilter(brand, category), Main.PerPage, page, totalpage);
        } else {
            pagingsql = service.BuildPagingSql(service.getTableName(), service.getConditionSearch(search, brand, category), Main.PerPage, page, totalpage);
        }
        List<Vehicle> lst = service.executeQuery(pagingsql);
        tableModel.setData(lst);
        tableVehicle.setModel(tableModel);
        tableVehicle.revalidate();
        tableVehicle.repaint();
    }

    private int getTotalPage() {
        int temptotal = totalpage.get();
        int temp = temptotal % Main.PerPage;
        if (temp == 0) {
            return (temptotal / Main.PerPage);
        } else {
            return (temptotal / Main.PerPage) + 1;
        }
    }

    private void fillPage() {
        comboVehicle.removeAllItems();
        for (int i = 1; i <= getTotalPage(); i++) {
            comboVehicle.addItem(i);
        }
        comboVehicle.setSelectedItem(curpage);
        comboVehicle.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                Object temppage = comboVehicle.getSelectedItem();
                if (temppage != null) {
                    setCurpage((Integer) temppage);
                }
            }
        });
        comboVehicle.revalidate();
        comboVehicle.repaint();
    }

    public void reloadData() {
        fillData(curpage);
        fillPage();
    }

    public void reInit() {
        initCbbFilter();
        fillData(curpage);
    }

    public void refresh() {
        cbbrand.setSelectedItem(Main.ALL);
        cbbcategory.setSelectedItem(Main.ALL);
        search = "";
        txtKeyword.setText(search);
        fillData(1);
        fillPage();
    }

    public boolean isNumeric(String str) {
        try {
            double d = Double.parseDouble(str);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableVehicle = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        comboVehicle = new javax.swing.JComboBox();
        txtKeyword = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbbrand = new javax.swing.JComboBox();
        cbbcategory = new javax.swing.JComboBox();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tableVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableVehicle);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel1.setLayout(new java.awt.FlowLayout(0));

        comboVehicle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboVehicleItemStateChanged(evt);
            }
        });
        comboVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVehicleActionPerformed(evt);
            }
        });
        jPanel1.add(comboVehicle);

        txtKeyword.setPreferredSize(new java.awt.Dimension(100, 25));
        txtKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeywordActionPerformed(evt);
            }
        });
        jPanel1.add(txtKeyword);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);

        cbbrand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbbrand);

        cbbcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbbcategory);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);

        jButton1.setText("Import");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void comboVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVehicleActionPerformed
    }//GEN-LAST:event_comboVehicleActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        callDialogVehicle(false);
    }//GEN-LAST:event_btnNewActionPerformed
    public Vehicle getSelectedVehicle() {
        int index = tableVehicle.getSelectedRow();
        if (index == -1) {
            return null;
        } else {
            return ((TableVehicleModel) tableVehicle.getModel()).getData(index);
        }
    }

    public Object getSelectedObject() {
        return getSelectedVehicle();
    }

    public void callDialogVehicle(boolean isedit) {
        Vehicle v = getSelectedVehicle();
        if (isedit && v == null) {
            JOptionPane.showMessageDialog(this, "Not selected a row.");
            return;
        }
        final CreateVehicleDialog creater = new CreateVehicleDialog(null, true);
        creater.setLocationRelativeTo(null);
        creater.setEditMode(isedit);
        if (isedit) {
            creater.setModel(v);
        }
        creater.setSaveListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                reInit();
                creater.dispose();
            }
        });
        creater.setVisible(true);
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        callDialogVehicle(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void comboVehicleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboVehicleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVehicleItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        search = txtKeyword.getText();
        fillData(1);
        fillPage();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Vehicle v = getSelectedVehicle();
        if (v == null) {
            JOptionPane.showMessageDialog(this, "Select a row to perform this action!");
            return;
        }
        final DialogImportOrderForm dialog = new DialogImportOrderForm(null, true);
        dialog.setLocationRelativeTo(null);
        dialog.setEditMode(false);
        dialog.setModel(v);
        dialog.setSaveListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                reloadData();
                dialog.dispose();
            }
        });
        dialog.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeywordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeywordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cbbcategory;
    private javax.swing.JComboBox cbbrand;
    private javax.swing.JComboBox comboVehicle;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVehicle;
    private javax.swing.JTextField txtKeyword;
    // End of variables declaration//GEN-END:variables
}
